[build-system]
requires = [
  "setuptools>=61.0.0",
  "wheel",
  "setuptools-git-versioning>=3.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "pymovements"
description = "A python package for processing eye movement data"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
maintainers = [
  {name = "Daniel Krakowczyk", email = "daniel.krakowczyk@uni-potsdam.de"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Typing :: Typed"
]
dependencies = [
  "deprecated>=1.2.18",
  "fastexcel>=0.13.0",
  "matplotlib>=3.8.0",
  "numpy>=1.22.4",
  "pandas>=2.1.4",
  "polars>=1.42.1",
  "pyarrow>=11.0.0",
  "pyopenssl>=22.0.0",
  "pyparsing>=3.1.2",
  "pyreadr>=0.5.2",
  "pyyaml>=6.0.2",
  "scikit-learn>=1.2",
  "scipy>=1.8.0",
  "tqdm>=4.63.0",
  "typing_extensions>=4.0.0"
]
dynamic = ["version"]

[project.optional-dependencies]
docs = [
  "ipykernel>=6.13.0",
  "ipywidgets>=8.1.7",
  "myst-nb>=1.0.0",
  "nbconvert>=7.0.0",
  "pandoc>=2.0.1",
  "pybtex>=0.25.0",
  "pydata-sphinx-theme>=0.12",
  "setuptools>=61.0.0",
  "sphinx>=7.0",
  "sphinx-copybutton>=0.5.0",
  "sphinx-favicon>=1.0.1",
  "sphinx_design>=0.3.0",
  "sphinx_mdinclude>=0.5.0",
  "sphinxcontrib.datatemplates>=0.9.2",
  "sphinxcontrib.bibtex>=2.4.2"
]
dev = [
  "codespell>=2.2",
  "covdefaults>=2.3.0",
  "tox>=4.12.0",
  "pybtex>=0.25.0",
  "pytest>=8.4.0",
  "pytest-benchmark>=5.1.0",
  "pytest-cov>=4.0.0",
  "pytest-doctestplus>=1.7.0",
  "pytest-remotedata>=0.4.1",
  "pytest-rerunfailures>=16.0",
  "setuptools>=61.0.0",
  "types-tqdm>=4.67.0",
  "pre-commit>=3.0.0",
  "pylint>=4.0.0"
]

[project.urls]
Homepage = "https://github.com/pymovements/pymovements"
"Source Code" = "https://github.com/pymovements/pymovements"
Documentation = "https://pymovements.readthedocs.io/en/stable"
"Bug Tracker" = "https://github.com/pymovements/pymovements/issues"
Changelog = "https://github.com/pymovements/pymovements/releases"

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
ignore-init-module-imports = true

[tool.autopep8]
max_line_length = 100
in-place = true
recursive = true
aggressive = 1

[tool.codespell]
skip = "./src/pymovements/_version.py,./.git/*,./.pytest_cache/*,tests/files/*,*.bib"
count = true
quiet-level = 3
ignore-words-list = 'bund,InstRead'

[tool.coverage.paths]
source = [
  'src/pymovements',
  '*/site-packages/pymovements',
  '*/src/pymovements'
]

[tool.coverage.report]
skip_covered = true
show_missing = true

[tool.coverage.run]
plugins = ['covdefaults']
parallel = true
branch = true
omit = [
  'docs/*',
  'src/pymovements/_version.py',
  'tests/*'
]

[tool.doc8]
max-line-length = 100

[tool.mypy]
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
disable_error_code = ["override"]

[[tool.mypy.overrides]]
module = "scipy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "sklearn.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "deprecated.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
check_untyped_defs = false
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = "docs.*"
check_untyped_defs = false
disallow_untyped_defs = false

[tool.pydoclint]
skip-checking-raises = true
treat-property-methods-as-class-attributes = true

[tool.pytest.ini_options]
addopts = "-ra -l --tb=long --doctest-modules --doctest-plus --remote-data=any --import-mode=importlib -p doctest_fixtures"
doctest_optionflags = "NORMALIZE_WHITESPACE"
filterwarnings = [
  "error",
  "ignore:pkg_resources is deprecated.*:UserWarning:pybtex",
  "ignore:pkg_resources is deprecated.*:DeprecationWarning:pybtex",
  "ignore:Deprecated call to `pkg_resources.declare_namespace.*:DeprecationWarning",
  "ignore:distutils Version classes are deprecated. Use packaging.version instead.:DeprecationWarning",
  "ignore:FigureCanvasAgg is non-interactive, and thus cannot be shown:UserWarning",
  "ignore:datetime.datetime.utcfromtimestamp() is deprecated.*:DeprecationWarning"
]
markers = ["network: mark a test as requiring network access"]
pythonpath = ['docs/source', 'tests/doctest']
testpaths = ['tests', 'src']
xfail_strict = true

[tool.setuptools.package-data]
pymovements = ["datasets/*.yaml"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools-git-versioning]
enabled = true
dev_template = "{tag}+post{ccount}.{sha}"
dirty_template = "{tag}+post{ccount}.{sha}.dirty"
